import { relations, sql } from "drizzle-orm";
import {
  type AnyPgColumn,
  bigint,
  boolean,
  date,
  check,
  customType,
  index,
  primaryKey,
  integer,
  jsonb,
  pgTable,
  pgView,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import type { C2pa } from "@/lib/c2pa";
import type { FieldType, FieldValues } from "@/lib/fields";
import type { Metadata } from "@/lib/metadata";
import type { ThemeSettings } from "@/lib/brand-theme";
import type { BrandState } from "@/lib/brand-files";
import type { CollectionIcon } from "@/lib/collection-icons";
import type { SnapRule, VersionKind } from "@/lib/history";
import type { Audience, PageLayout, PageText, RequestKind, Section, SnapPage } from "@/lib/pages";
import type { Actor, EventKind, Surface } from "@/lib/insights";
import type { Origin, Rights } from "@/lib/rights";
import type { RuleSpec, RuleType, RuleValue } from "@/lib/rules";
import type { Scope } from "@/lib/scopes";
import type { Resource } from "@/lib/access";
import type { Status } from "@/lib/lifecycle";
import type { PortalAccess, PortalPreset, PortalSite, PortalTheme } from "@/lib/portal";

export type AssetStatus = Status;

const tsvector = customType<{ data: string }>({ dataType: () => "tsvector" });

/**
 * Assets are content-addressed: `sha256` is the identity of the bytes, and the
 * storage key is derived from it. Uploading the same file twice is a no-op.
 *
 */
export const assets = pgTable(
  "assets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
    /** Unique within a workspace. Storage is keyed by it alone, so workspaces share identical bytes. */
    sha256: text("sha256").notNull(),
    filename: text("filename").notNull(),
    mime: text("mime").notNull(),
    size: integer("size").notNull(),
    /** Only people with a grant on it (or a collection it is in) and admins see it (lib/access.ts). */
    private: boolean("private").notNull().default(false),
    /**
     * Served at /a/{id} to anyone, for embedding, while it may be used
     * (lib/lifecycle.ts). Otherwise only people who can see it, and holders of
     * a signed URL (lib/signed.ts), get the bytes.
     */
    public: boolean("public").notNull().default(false),
    width: integer("width"),
    height: integer("height"),
    /** Freeform probe output (format, pages, colour space). */
    probe: jsonb("probe").$type<Record<string, unknown>>(),
    /** EXIF / IPTC / XMP read from the file on ingest. See lib/metadata.ts. */
    metadata: jsonb("metadata").$type<Metadata>(),
    /** Lowercased and deduped by lib/tags.ts before they get here. */
    tags: jsonb("tags").$type<string[]>().notNull().default([]),
    /** Values for the library's custom fields, keyed by `fields.key`. */
    fields: jsonb("fields").$type<FieldValues>().notNull().default({}),
    /**
     * Values this asset inherits from its collections, materialized by
     * lib/core/collections.ts whenever membership or a collection changes, so
     * search and filters read one row. The asset's own `fields` win over these.
     */
    inherited: jsonb("inherited").$type<FieldValues>().notNull().default({}),
    /**
     * Where it is in its lifecycle (lib/lifecycle.ts): `draft`, `proposed` (in
     * review) until a human promotes it, which is what a propose-scoped key (an
     * agent) uploads, `active` (approved), `archived`, `rejected`. Expired is
     * derived from `rights`. Default searches show approved, unexpired assets.
     */
    status: text("status").$type<AssetStatus>().notNull().default("active"),
    /**
     * Who proposed it: the API key's name, or "web". Kept after review, so a
     * person sees who sent what and an agent can find its own proposals.
     */
    proposedBy: text("proposed_by"),
    /**
     * Why a person rejected it. A rejected asset is kept, out of the library
     * and the review queue, so the agent that proposed it can read the reason.
     */
    reviewNote: text("review_note"),
    /** Tags an agent suggested, waiting for a human to accept or dismiss. */
    proposedTags: jsonb("proposed_tags").$type<string[]>().notNull().default([]),
    /** Custom field values an agent suggested, keyed like `fields`, waiting for a human to accept or dismiss. */
    proposedFields: jsonb("proposed_fields").$type<FieldValues>().notNull().default({}),
    /** License, territories, channels, embargo, expiry, model release (lib/rights.ts); null says nothing. */
    rights: jsonb("rights").$type<Rights>(),
    /** How it came to be: shot, licensed, or generated by a model. */
    origin: text("origin").$type<Origin>(),
    /** What it was made from: the photo an edit started from, the image a model was given. */
    parentAssetId: uuid("parent_asset_id").references((): AnyPgColumn => assets.id, { onDelete: "set null" }),
    /** The tool or model that made it, e.g. "gpt-image 2.0". */
    generator: text("generator"),
    prompt: text("prompt"),
    /** C2PA Content Credentials read on ingest (lib/c2pa.ts); the original keeps the manifest itself. */
    c2pa: jsonb("c2pa").$type<C2pa>(),
    /**
     * How it arrived, when not from a person: `agent`, through an API key;
     * `import`, brought in from outside by the server (an icon set, Google
     * Fonts, a template). The review queue's chips read it.
     */
    via: text("via").$type<"agent" | "import">(),
    /** The asset that replaces this one. /api/v1/check refuses a replaced asset and names this. */
    supersededBy: uuid("superseded_by").references((): AnyPgColumn => assets.id, { onDelete: "set null" }),
    /**
     * Versions of one thing share a stack: the id of the asset it started
     * from, kept as a plain value so the stack outlives that asset. Null for
     * an asset with one version (lib/core/versions.ts).
     */
    stackId: uuid("stack_id"),
    /** 1, 2, 3 within the stack. */
    version: integer("version"),
    /**
     * The stack's current approved version: the one the library shows, share
     * links serve, and every other approved version is superseded by.
     */
    current: boolean("current").notNull().default(false),
    /**
     * Deleted, and restorable until lib/core/sweep.ts purges it 30 days on.
     * Its bytes stay until then; it reads `state: "deleted"` and is served to nobody.
     */
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    /**
     * Maintained by Postgres, so it cannot drift from the columns it indexes.
     * 'simple' rather than 'english': asset search is names and keywords, where
     * stemming "logos" to "logo" matters less than matching "fox_v3" by "fox".
     * Filenames are split on . _ - first, since the parser keeps "fox_v3.png"
     * as one token.
     */
    search: tsvector("search")
      .notNull()
      .generatedAlwaysAs(
        sql`setweight(to_tsvector('simple', regexp_replace(filename, '[._-]+', ' ', 'g')), 'A') || setweight(to_tsvector('simple', tags), 'A') || setweight(jsonb_to_tsvector('simple', coalesce(metadata, '{}'), '["string"]'), 'B') || setweight(jsonb_to_tsvector('simple', fields || inherited, '["string"]'), 'B')`,
      ),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    unique("assets_workspace_sha256_unique").on(t.workspaceId, t.sha256),
    index("assets_workspace_created_at_idx").on(t.workspaceId, t.createdAt.desc()),
    // Whether anything still holds some bytes, across workspaces: the sweeper asks.
    index("assets_sha256_idx").on(t.sha256),
    index("assets_deleted_at_idx").on(t.deletedAt).where(sql`${t.deletedAt} is not null`),
    index("assets_search_idx").using("gin", t.search),
    index("assets_tags_idx").using("gin", sql`${t.tags} jsonb_path_ops`),
    // Field filters match the effective value, own over inherited: `inherited || fields`.
    index("assets_effective_fields_idx").using("gin", sql`(${t.inherited} || ${t.fields}) jsonb_path_ops`),
    check("assets_status_check", sql`${t.status} in ('draft', 'proposed', 'active', 'archived', 'rejected')`),
    index("assets_proposed_by_idx").on(t.proposedBy),
    check("assets_origin_check", sql`${t.origin} in ('shot', 'licensed', 'generated')`),
    check("assets_via_check", sql`${t.via} in ('agent', 'import')`),
    check("assets_not_superseded_by_self", sql`${t.supersededBy} <> ${t.id}`),
    unique("assets_stack_version_unique").on(t.stackId, t.version),
    uniqueIndex("assets_one_current").on(t.stackId).where(sql`${t.current}`),
    check("assets_stacked_check", sql`(${t.stackId} is null) = (${t.version} is null)`),
  ],
);

export type Asset = typeof assets.$inferSelect;
export type NewAsset = typeof assets.$inferInsert;

/** A named set of assets that can carry field values its members inherit. */
export const collections = pgTable("collections", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  /** A Tabler icon name from lib/collection-icons.ts; null shows a folder. */
  icon: text("icon"),
  fields: jsonb("fields").$type<FieldValues>().notNull().default({}),
  /** Only people with a grant on it and admins see it; assets in private collections only are private too. */
  private: boolean("private").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .default(sql`now()`),
});

export const collectionAssets = pgTable(
  "collection_assets",
  {
    collectionId: uuid("collection_id")
      .notNull()
      .references(() => collections.id, { onDelete: "cascade" }),
    assetId: uuid("asset_id")
      .notNull()
      .references(() => assets.id, { onDelete: "cascade" }),
  },
  (t) => [
    primaryKey({ columns: [t.collectionId, t.assetId] }),
    // The primary key serves "members of a collection"; this serves "collections of an asset".
    index("collection_assets_asset_idx").on(t.assetId),
  ],
);

/**
 * A workspace's custom field schema. `key` is the identity: it is what asset
 * values are stored under, so it and `type` never change once created. Make a
 * new field instead.
 */
export const fields = pgTable(
  "fields",
  {
  workspaceId: uuid("workspace_id")
    .notNull()
    .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
  key: text("key").notNull(),
  label: text("label").notNull(),
  type: text("type").$type<FieldType>().notNull(),
  options: jsonb("options").$type<string[]>().notNull().default([]),
  required: boolean("required").notNull().default(false),
  position: integer("position").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .default(sql`now()`),
  },
  (t) => [
    primaryKey({ columns: [t.workspaceId, t.key] }),
    check("fields_type_check", sql`${t.type} in ('text', 'number', 'date', 'boolean', 'select')`),
  ],
);

/**
 * A named query. `query` is the /api/v1/assets query string, validated when
 * saved, so running one is a plain GET any client can make.
 */
export const savedSearches = pgTable("saved_searches", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  query: text("query").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .default(sql`now()`),
});

/**
 * API keys, one workspace each. Only a SHA-256 of the secret is stored: keys
 * are 256 random bits, so a fast hash is enough and a leaked table leaks no usable key. `prefix`
 * is the first characters of the secret, to tell keys apart in a list.
 */
export const apiKeys = pgTable(
  "api_keys",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /**
     * A key works in one workspace, with one scope there. An agent a person
     * connected to several workspaces at once holds one secret, so one
     * `hash`, with a row in each (lib/core/oauth.ts): the request says which
     * one it means, else it is in the oldest.
     */
    workspaceId: uuid("workspace_id")
      .notNull()
      .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    prefix: text("prefix").notNull(),
    hash: text("hash").notNull(),
    scope: text("scope").$type<Scope>().notNull(),
    /**
     * Whose agent this is, for a key minted by OAuth or `artbucket login`
     * (lib/core/oauth.ts): it can never do more than they can, and goes
     * with them. Null for a key an admin made, which answers to nobody.
     */
    userId: text("user_id").references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
    /**
     * An agent's token works until then (lib/core/oauth.ts): an hour, renewed
     * by its refresh token. Null for a key an admin made, which lasts until
     * revoked.
     */
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    /** The refresh token that renews it (sha256), until then; a key that can no longer be renewed is swept. */
    refreshHash: text("refresh_hash"),
    refreshExpiresAt: timestamp("refresh_expires_at", { withTimezone: true }),
    /** The OAuth client it was issued to: only that client renews it, and a client holding no key is swept. */
    clientId: text("client_id").references((): AnyPgColumn => oauthClients.id, { onDelete: "set null" }),
    /** Bumped on every request that presents it: "Connected agents" and "waiting for first call". */
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
    calls: integer("calls").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    check("api_keys_scope_check", sql`${t.scope} in ('read', 'propose', 'write', 'admin')`),
    unique("api_keys_hash_workspace_unique").on(t.hash, t.workspaceId),
    index("api_keys_refresh_hash_idx").on(t.refreshHash),
  ],
);

export type Visibility = "private" | "public";

/**
 * A brand: its own rules and its own history. Exactly one per workspace is the default,
 * which is what /brand and an unqualified /api/v1/brand/rules mean.
 */
export const brands = pgTable(
  "brands",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    isDefault: boolean("is_default").notNull().default(false),
    /** How its pages look (lib/brand-theme.ts ThemeSettings): only what was set, the rest read from the rules. */
    theme: jsonb("theme").$type<ThemeSettings>().notNull().default({}),
    /**
     * Who sees it on BrandHub (lib/core/hub.ts), at {org}/{brand}: its workspace's people
     * (`private`), or anyone and any agent (`public`). Either way, its latest publish.
     */
    visibility: text("visibility").$type<Visibility>().notNull().default("private"),
    /** The portal BrandHub links as its guidelines; null: its first public portal, if any. */
    hubPortalId: uuid("hub_portal_id").references((): AnyPgColumn => portals.id, { onDelete: "set null" }),
    /**
     * Taken off BrandHub by whoever runs the server, and why (docs: portals,
     * BrandHub): while set, the brand can't be made public again. Written in
     * the database only, never through the API, so its organization can't
     * undo it on its own.
     */
    hubDelisted: text("hub_delisted"),
    /** The BrandHub brand it started from, as {org}/{brand}@{n} (lib/core/hub.ts startFrom); null for any other start. */
    forkedFrom: text("forked_from"),
    /**
     * The brand's own domain, a lower-cased host without www (acme.com): from its brand.json, a
     * template, or Settings. Several brands may name one, across organizations: whoever proves it
     * may claim their listings (lib/core/hub-trust.ts).
     */
    domain: text("domain"),
    /**
     * The listing that took its place on BrandHub, as {org}/{brand}, once whoever proved its
     * domain claimed it (lib/core/hub-claims.ts): it is private, can't be made public again, and
     * its hub address leads there for good.
     */
    hubMovedTo: text("hub_moved_to"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    check("brands_visibility_check", sql`${t.visibility} in ('private', 'public')`),
    unique("brands_workspace_slug_unique").on(t.workspaceId, t.slug),
    uniqueIndex("brands_one_default").on(t.workspaceId).where(sql`${t.isDefault}`),
    index("brands_domain_idx").on(t.domain),
  ],
);

/**
 * The canon: one brand rule per (brand, key, context). A null context is the default;
 * see lib/rules.ts for how a context resolves. `value` is checked against
 * `type` by lib/rules.ts, and `type` never changes: delete and recreate.
 */
export const brandRules = pgTable(
  "brand_rules",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    key: text("key").notNull(),
    context: text("context"),
    type: text("type").$type<RuleType>().notNull(),
    /** The heading readers see; null reads the key in words. Keys never change with it. */
    label: text("label"),
    value: jsonb("value").$type<RuleValue>().notNull(),
    /** Details beyond the value, checked against `type` (lib/rules.ts RULE_SPEC). */
    spec: jsonb("spec").$type<RuleSpec>(),
    usage: text("usage"),
    /** Order on the page. Shared by a key's context versions, so they move together. */
    position: integer("position").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    unique("brand_rules_brand_key_context_unique").on(t.brandId, t.key, t.context).nullsNotDistinct(),
    check("brand_rules_type_check", sql`${t.type} in ('color', 'text', 'number', 'list', 'font')`),
  ],
);

/**
 * Assets a rule points at, in order: the logo it governs, examples of doing it
 * right. Real foreign keys, so deleting an asset drops it from every rule.
 */
export const brandRuleAssets = pgTable(
  "brand_rule_assets",
  {
    ruleId: uuid("rule_id")
      .notNull()
      .references(() => brandRules.id, { onDelete: "cascade" }),
    assetId: uuid("asset_id")
      .notNull()
      .references(() => assets.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
    /** A rendition spec (lib/transform.ts), e.g. w_512,f_png: the rule means this size, not the original. */
    rendition: text("rendition"),
  },
  (t) => [primaryKey({ columns: [t.ruleId, t.assetId] }), index("brand_rule_assets_asset_idx").on(t.assetId)],
);

/**
 * A brand's history: the whole rule set after each change (lib/history.ts).
 * Edits close together by the same actor extend the latest version instead of
 * starting one, so the list reads like a doc's, not like a keystroke log.
 */
export const brandVersions = pgTable(
  "brand_versions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    /** 1, 2, 3 within the brand. */
    number: integer("number").notNull(),
    kind: text("kind").$type<VersionKind>().notNull(),
    /** Set by a person to keep a version as a checkpoint; named versions are never extended. */
    name: text("name"),
    /** Who made it: an API key's name, or "web" for the app without a key. */
    actor: text("actor").notNull(),
    /** For a restore: the version it put back. */
    restoredFrom: integer("restored_from"),
    /** Keys touched, in order, for the one-line summary. */
    changed: jsonb("changed").$type<string[]>().notNull().default([]),
    snapshot: jsonb("snapshot").$type<SnapRule[]>().notNull(),
    /** The brand's pages as they stood; null in versions from before pages, which a restore leaves alone. */
    pages: jsonb("pages").$type<SnapPage[]>(),
    /** The brand's theme settings; null in versions from before themes, which a restore leaves alone. */
    theme: jsonb("theme").$type<ThemeSettings>(),
    /** Set when this version was published: portals show it, and later edits start a new version. */
    publishedAt: timestamp("published_at", { withTimezone: true }),
    publishedBy: text("published_by"),
    /** What the publish said, for readers' "what's new", and a picture with it. */
    note: text("note"),
    noteImage: uuid("note_image"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    unique("brand_versions_brand_number_unique").on(t.brandId, t.number),
    check("brand_versions_kind_check", sql`${t.kind} in ('baseline', 'edit', 'restore')`),
  ],
);

/**
 * A brand's pages: guidelines laid out for people, over its rules
 * (lib/pages.ts). Sections are stored whole, in order, since a page is always
 * read and written whole; they bind rules by key, never by value.
 */
export const brandPages = pgTable(
  "brand_pages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    slug: text("slug").notNull(),
    title: text("title").notNull(),
    position: integer("position").notNull().default(0),
    hidden: boolean("hidden").notNull().default(false),
    sections: jsonb("sections").$type<Section[]>().notNull().default([]),
    /** The page it sits under, by slug: ids change on every restore (core/page-store.ts writePages). */
    parent: text("parent"),
    eyebrow: text("eyebrow"),
    lede: text("lede"),
    /** No foreign key: a restored snapshot can name an asset purged since, and reads leave it out. */
    cover: uuid("cover"),
    icon: text("icon").$type<CollectionIcon>(),
    audience: text("audience").$type<Audience>().notNull().default("everyone"),
    tabs: boolean("tabs").notNull().default(false),
    /** Slugs it had before a rename, so old links keep working. */
    aliases: text("aliases").array().notNull().default(sql`'{}'::text[]`),
    /** Its title, eyebrow and lede in other languages, by language tag; null for none. */
    translations: jsonb("translations").$type<Record<string, PageText>>(),
    layout: text("layout").$type<PageLayout>().notNull().default("book"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    /** The last change to what it says, not to where it sits. */
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    unique("brand_pages_brand_slug_unique").on(t.brandId, t.slug),
    check("brand_pages_audience_check", sql`${t.audience} in ('everyone', 'partners', 'members')`),
    check("brand_pages_layout_check", sql`${t.layout} in ('book', 'landing')`),
  ],
);

/**
 * Review comments on a brand's pages (lib/core/brand-comments.ts), pinned to
 * a section or to the page as a whole, the way a design tool's are: a root
 * starts a thread, replies point at it through `parentId`, and only a root is
 * resolved. Not part of the guidelines: no history, never published. `page`
 * and `section` are slugs and ids as they were, not keys: a renamed page
 * still finds its comments through its aliases, and a section deleted since
 * leaves them on the page. `author` is the name as it read then, so a comment
 * outlives its person; `authorId` or `authorKey` says whose it is.
 */
export const brandComments = pgTable(
  "brand_comments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    page: text("page").notNull(),
    /** A section's id on the page; null for the page as a whole. */
    section: text("section"),
    /** The thread's root; null for a root. Deleting a root takes its replies. */
    parentId: uuid("parent_id").references((): AnyPgColumn => brandComments.id, { onDelete: "cascade" }),
    body: text("body").notNull(),
    authorId: text("author_id").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
    /** The API key that wrote it, for an agent's own; not a foreign key, as in `audit`. */
    authorKey: uuid("author_key"),
    author: text("author").notNull(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    resolvedBy: text("resolved_by"),
    /** When its body last changed: "edited" beside it. Resolving is not an edit. */
    editedAt: timestamp("edited_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("brand_comments_brand_page_idx").on(t.brandId, t.page),
    index("brand_comments_parent_idx").on(t.parentId),
    check("brand_comments_body_check", sql`char_length(${t.body}) between 1 and 4000`),
    check("brand_comments_resolved_check", sql`${t.parentId} is null or ${t.resolvedAt} is null`),
  ],
);

/**
 * Where a brand also lives as files, in a Git repository (brand as code,
 * core/brand-sync.ts): the repository, its branch and the folder the brand's
 * files sit in. `base` is the brand as those files said it at `commit`, the
 * last state both sides agreed on: a sync merges each side's changes since
 * then. `paths` names the assets that are files in the repository, by id,
 * so writing the brand out names them by path again. What pushes and pulls
 * (a Git host's app, the CLI) is outside the core: it calls the API.
 */
export const brandSources = pgTable("brand_sources", {
  brandId: uuid("brand_id")
    .primaryKey()
    .references(() => brands.id, { onDelete: "cascade" }),
  /** The repository's address, as its host shows it: https://github.com/acme/brand. */
  remote: text("remote").notNull(),
  branch: text("branch").notNull().default("main"),
  /** The brand's folder in the repository; empty for its root. */
  path: text("path").notNull().default(""),
  commit: text("commit"),
  base: jsonb("base").$type<BrandState>(),
  paths: jsonb("paths").$type<Record<string, string>>().notNull().default({}),
  syncedAt: timestamp("synced_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * A brand as a proposed change says it (a pull request's files), to read
 * before it lands: never the brand's draft, never published. Opened by its
 * `token`, a random capability in its link, until it expires; one per
 * brand and `ref`, so a pull request keeps its link as it changes.
 */
export const brandPreviews = pgTable(
  "brand_previews",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    /** What proposes it, as its host names it: pull/12, a branch. */
    ref: text("ref").notNull(),
    title: text("title"),
    commit: text("commit"),
    token: text("token").notNull().unique(),
    state: jsonb("state").$type<BrandState>().notNull(),
    actor: text("actor").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  },
  (t) => [unique("brand_previews_brand_ref_unique").on(t.brandId, t.ref), check("brand_previews_ref_check", sql`char_length(${t.ref}) between 1 and 200`)],
);

export type ActivityVerb =
  | "added"
  | "suggested"
  | "approved"
  | "rejected"
  | "deleted"
  | "suggested_tags"
  | "suggested_fields"
  | "archived"
  | "unarchived"
  | "made_current"
  | "restored";

/**
 * What happened to assets, and who did it: a person by name, an API key by
 * name, a share link's guest, or "web" for the app without an account. Brand rule changes are not here: brand_versions already
 * keeps them, and /api/v1/activity reads both. `assetId` is not a foreign
 * key: an asset's history outlives the asset.
 */
export const activity = pgTable(
  "activity",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
    at: timestamp("at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    actor: text("actor").notNull(),
    /** Done with an API key: an agent or a script, not a person in the app. */
    agent: boolean("agent").notNull().default(false),
    verb: text("verb").$type<ActivityVerb>().notNull(),
    assetId: uuid("asset_id"),
    /** The asset's title or filename when it happened, so a deleted one still reads. */
    label: text("label").notNull(),
    /** Suggested tags or fields, a rejection's reason, the version it is. */
    detail: jsonb("detail").$type<{ tags?: string[]; fields?: string[]; note?: string; version?: number }>(),
  },
  (t) => [index("activity_workspace_at_idx").on(t.workspaceId, t.at.desc())],
);

// ---- people -----------------------------------------------------------------

/**
 * Accounts, as better-auth keeps them (lib/auth.ts): who someone is. What they
 * may do is `grants`, which is ours.
 */
export const users = pgTable("users", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const sessions = pgTable(
  "sessions",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    token: text("token").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    // Where it was made: an organization's domain for the app, or APP_URL's origin. Used anywhere else, it is no session (lib/auth.ts).
    // Null: made before this was kept, good at APP_URL's only.
    origin: text("origin"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("sessions_user_idx").on(t.userId)],
);

/** A way to sign in: a password (`providerId` "credential") or an OIDC identity. */
export const accounts = pgTable(
  "accounts",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("accounts_user_idx").on(t.userId)],
);

/**
 * So better-auth reads a session with its person, or a person with their
 * ways to sign in, in one query rather than two (lib/auth.ts `joins`).
 */
export const usersRelations = relations(users, ({ many }) => ({ sessions: many(sessions), accounts: many(accounts) }));
export const sessionsRelations = relations(sessions, ({ one }) => ({ user: one(users, { fields: [sessions.userId], references: [users.id] }) }));
export const accountsRelations = relations(accounts, ({ one }) => ({ user: one(users, { fields: [accounts.userId], references: [users.id] }) }));

/**
 * OAuth clients that registered themselves (RFC 7591): Claude, ChatGPT, the
 * CLI. Public clients, no secret: PKCE stands in for one. What a client is
 * granted is an API key (lib/core/oauth.ts), so this is only its name and
 * where it may be sent back to.
 */
export const oauthClients = pgTable("oauth_clients", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  redirectUris: jsonb("redirect_uris").$type<string[]>().notNull().default([]),
  /** The grants it registered for (RFC 7591): one without refresh_token gets a longer token and none to renew it. Null: registered before they were kept. */
  grantTypes: jsonb("grant_types").$type<string[]>(),
  /** When a token was last issued or renewed for it: a client unused for long, holding no key, is swept (lib/core/oauth.ts). */
  usedAt: timestamp("used_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** better-auth's, and ours for OAuth codes waiting to be exchanged (lib/core/oauth.ts). */
export const verifications = pgTable("verifications", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * An organization's own single sign-on (lib/core/sso.ts): one OpenID Connect
 * provider for the people at one email domain, which it proves by a TXT
 * record. better-auth's sso plugin reads it to sign them in (lib/auth.ts);
 * its column names are the plugin's. `providerId` is the organization's id,
 * so the redirect URI the provider holds never changes.
 */
export const ssoProviders = pgTable("sso_providers", {
  id: text("id").primaryKey(),
  providerId: text("provider_id").notNull().unique(),
  organizationId: uuid("organization_id")
    .notNull()
    .unique()
    .references(() => organizations.id, { onDelete: "cascade" }),
  /** Who set it up. */
  userId: text("user_id").references(() => users.id, { onDelete: "set null" }),
  issuer: text("issuer").notNull(),
  /** JSON: the client, and the endpoints discovered from the issuer when it was saved. */
  oidcConfig: text("oidc_config").notNull(),
  samlConfig: text("saml_config"),
  /** One organization's at a time: sign-in finds the provider by it. */
  domain: text("domain").notNull().unique(),
  domainVerified: boolean("domain_verified").notNull().default(false),
  /** Addresses at the domain sign in only through it: no password, but for the organization's admins (lib/core/sso.ts). */
  required: boolean("required").notNull().default(false),
  /** What the TXT record holds. Nullable only because better-auth refuses a required column it never writes. */
  token: text("token"),
  /** Where its people land the first time, able to read: null for the organization's oldest workspace. */
  workspaceId: uuid("workspace_id").references(() => workspaces.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---- tenancy and access -----------------------------------------------------

/** A team, or a client of an agency: people, and the workspaces they share. */
export const organizations = pgTable("organizations", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * A library: its own assets, collections, fields, brands, searches and keys.
 * Nothing crosses from one workspace to another but the stored bytes.
 */
export const workspaces = pgTable(
  "workspaces",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique("workspaces_org_slug_unique").on(t.organizationId, t.slug)],
);

/**
 * What a person may do, and where: a scope (lib/scopes.ts) on an
 * organization, a workspace, a collection or one asset. Grants add up and
 * reach down: admin on the organization is admin in every workspace, write on
 * a collection is write on its assets (lib/access.ts). Having one is being a
 * member. `resourceId` names the thing; it is not a foreign key, so core
 * deletes a collection's or an asset's grants with it.
 */
export const grants = pgTable(
  "grants",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    /** Null for a grant on the organization itself. */
    workspaceId: uuid("workspace_id").references(() => workspaces.id, { onDelete: "cascade" }),
    resource: text("resource").$type<Resource>().notNull(),
    resourceId: uuid("resource_id").notNull(),
    scope: text("scope").$type<Scope>().notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique("grants_user_resource_unique").on(t.userId, t.resource, t.resourceId),
    index("grants_org_idx").on(t.organizationId),
    check("grants_resource_check", sql`${t.resource} in ('organization', 'workspace', 'collection', 'asset')`),
    check("grants_scope_check", sql`${t.scope} in ('read', 'propose', 'write', 'admin')`),
    check("grants_workspace_check", sql`(${t.resource} = 'organization') = (${t.workspaceId} is null)`),
  ],
);

/**
 * A grant waiting for someone to take it. The link carries the token, found
 * by its hash; the token itself is kept sealed, so an admin can copy the
 * link again. `email` is who it was meant for.
 */
export const invitations = pgTable(
  "invitations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    workspaceId: uuid("workspace_id").references(() => workspaces.id, { onDelete: "cascade" }),
    email: text("email").notNull(),
    resource: text("resource").$type<Resource>().notNull(),
    resourceId: uuid("resource_id").notNull(),
    scope: text("scope").$type<Scope>().notNull(),
    tokenHash: text("token_hash").notNull().unique(),
    /** The token again, sealed (lib/settings.ts seal), so an admin can copy the link later. Lookups use the hash. */
    tokenSealed: text("token_sealed"),
    invitedBy: text("invited_by").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    acceptedBy: text("accepted_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("invitations_org_idx").on(t.organizationId),
    check("invitations_scope_check", sql`${t.scope} in ('read', 'propose', 'write', 'admin')`),
  ],
);

export type ShareKind = "view" | "upload";

/**
 * A link for people without an account. `view` shows a collection or one
 * asset; `upload` takes files into a collection (or the workspace) as
 * proposals. The token is kept as is, so its maker can copy the link again:
 * a password (scrypt, lib/share.ts) is what protects one that matters.
 */
export const shareLinks = pgTable(
  "share_links",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    kind: text("kind").$type<ShareKind>().notNull(),
    collectionId: uuid("collection_id").references(() => collections.id, { onDelete: "cascade" }),
    assetId: uuid("asset_id").references(() => assets.id, { onDelete: "cascade" }),
    name: text("name"),
    token: text("token").notNull().unique(),
    passwordHash: text("password_hash"),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    createdBy: text("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("share_links_workspace_idx").on(t.workspaceId),
    check("share_links_kind_check", sql`${t.kind} in ('view', 'upload')`),
    check(
      "share_links_target_check",
      sql`(${t.kind} = 'view' and num_nonnulls(${t.collectionId}, ${t.assetId}) = 1) or (${t.kind} = 'upload' and ${t.assetId} is null)`,
    ),
  ],
);

/**
 * Who changed who may do what: sign-ins, members, grants, invitations, keys,
 * share links, workspaces. What happened to assets is `activity`; this is the
 * trail a security review reads. Rows outlive what they name.
 */
export const audit = pgTable(
  "audit",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
    /** Null for what belongs to a person, not an organization: signing in. */
    organizationId: uuid("organization_id"),
    workspaceId: uuid("workspace_id"),
    actor: text("actor").notNull(),
    userId: text("user_id"),
    keyId: uuid("key_id"),
    action: text("action").notNull(),
    /** What it was done to, as it read then: an email, a key's name, a collection. */
    target: text("target"),
    detail: jsonb("detail").$type<Record<string, unknown>>(),
    ip: text("ip"),
  },
  (t) => [index("audit_org_at_idx").on(t.organizationId, t.at.desc()), index("audit_user_idx").on(t.userId)],
);

/**
 * Settings (lib/settings.ts): one row per key and place, an organization's or
 * a workspace's. Secret properties are sealed before they get here.
 */
export const settings = pgTable(
  "settings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    /** Null for the organization's own. */
    workspaceId: uuid("workspace_id").references(() => workspaces.id, { onDelete: "cascade" }),
    key: text("key").notNull(),
    value: jsonb("value").$type<Record<string, unknown>>().notNull(),
    updatedBy: text("updated_by").notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique("settings_place_key_unique").on(t.organizationId, t.workspaceId, t.key).nullsNotDistinct()],
);

/**
 * Delivery traffic: what /a/{id} served, per workspace and day (lib/core/usage.ts).
 * Counted by the delivery route, read in Settings, Usage.
 */
export const traffic = pgTable(
  "traffic",
  {
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    day: date("day", { mode: "string" }).notNull(),
    requests: integer("requests").notNull().default(0),
    bytes: bigint("bytes", { mode: "number" }).notNull().default(0),
  },
  (t) => [primaryKey({ columns: [t.workspaceId, t.day] })],
);

// ---- portals ------------------------------------------------------------------

/**
 * A brand portal (lib/core/portals.ts): chosen collections and brands, themed, at
 * /p/{slug} or a domain of its own, for people outside the team. It shows
 * only approved, unexpired, current assets, and offers renditions made for a
 * purpose rather than raw originals. Who gets in: anyone (`public`), whoever
 * has the password, or people with access to the workspace (`members`); an
 * approved access request lets someone in either of the last two.
 */
export const portals = pgTable(
  "portals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    /** Its address: /p/{slug}. Unique on the server. */
    slug: text("slug").notNull().unique(),
    name: text("name").notNull(),
    /** A few paragraphs under the name: what this is, who it is for, who to ask. */
    intro: text("intro"),
    access: text("access").$type<PortalAccess>().notNull().default("public"),
    passwordHash: text("password_hash"),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    presets: jsonb("presets").$type<PortalPreset[]>().notNull().default(["web", "print", "social"]),
    theme: jsonb("theme").$type<PortalTheme>().notNull().default({ logo: null, accent: null, background: null }),
    /** The site around its pages: footer, quick grab, terms, and whether search engines may list it (lib/portal.ts PortalSite). */
    site: jsonb("site").$type<PortalSite>().notNull().default({}),
    createdBy: text("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("portals_workspace_idx").on(t.workspaceId),
    check("portals_access_check", sql`${t.access} in ('public', 'password', 'members')`),
    check("portals_password_check", sql`${t.access} <> 'password' or ${t.passwordHash} is not null`),
  ],
);

/**
 * A portal's addresses before a rename, its last five (lib/core/portals.ts
 * ALIASES): each still leads to it (src/proxy.ts redirects), and nobody else
 * may take one while the portal stands. Deleting the portal frees them.
 */
export const portalAliases = pgTable("portal_aliases", {
  slug: text("slug").primaryKey(),
  portalId: uuid("portal_id")
    .notNull()
    .references(() => portals.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** A portal's collections, in the order it shows them. Deleting a collection takes it off every portal. */
export const portalCollections = pgTable(
  "portal_collections",
  {
    portalId: uuid("portal_id")
      .notNull()
      .references(() => portals.id, { onDelete: "cascade" }),
    collectionId: uuid("collection_id")
      .notNull()
      .references(() => collections.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
  },
  (t) => [primaryKey({ columns: [t.portalId, t.collectionId] }), index("portal_collections_collection_idx").on(t.collectionId)],
);

/** A portal's brands, in the order its tabs show them: each brand's guidelines, read-only. Deleting a brand takes it off every portal. */
export const portalBrands = pgTable(
  "portal_brands",
  {
    portalId: uuid("portal_id")
      .notNull()
      .references(() => portals.id, { onDelete: "cascade" }),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
  },
  (t) => [primaryKey({ columns: [t.portalId, t.brandId] }), index("portal_brands_brand_idx").on(t.brandId)],
);

export type PortalRequestStatus = "pending" | "approved" | "denied";

/**
 * Someone outside asking into a portal that isn't public. Approved, they get
 * a key of their own, found by its hash and kept sealed so the link can be
 * copied again; it stops at `expiresAt` or when the request is deleted.
 * A request section (lib/pages.ts) asks for an asset, a review or an answer
 * instead, from the page and section it sits in.
 */
export const portalRequests = pgTable(
  "portal_requests",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    portalId: uuid("portal_id")
      .notNull()
      .references(() => portals.id, { onDelete: "cascade" }),
    email: text("email").notNull(),
    name: text("name"),
    /** Who they are and what they need it for, in their words. */
    note: text("note"),
    status: text("status").$type<PortalRequestStatus>().notNull().default("pending"),
    kind: text("kind").$type<RequestKind>().notNull().default("access"),
    /** Where a request section asked from: a page slug and a section id, as they were then. */
    page: text("page"),
    section: text("section"),
    keyHash: text("key_hash").unique(),
    keySealed: text("key_sealed"),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    decidedBy: text("decided_by"),
    decidedAt: timestamp("decided_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("portal_requests_portal_idx").on(t.portalId, t.createdAt.desc()),
    check("portal_requests_status_check", sql`${t.status} in ('pending', 'approved', 'denied')`),
    check("portal_requests_kind_check", sql`${t.kind} in ('access', 'asset', 'review', 'question')`),
  ],
);

/**
 * How often a portal's pages were read, per brand, page and day
 * (lib/core/usage.ts), for the 30 days of views an admin sees per page.
 * ponytail: pages only; per-asset downloads come with the v1.3 analytics.
 */
export const pageViews = pgTable(
  "page_views",
  {
    portalId: uuid("portal_id")
      .notNull()
      .references(() => portals.id, { onDelete: "cascade" }),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    /** The page's slug when it was read. */
    page: text("page").notNull(),
    day: date("day", { mode: "string" }).notNull(),
    views: integer("views").notNull().default(0),
  },
  (t) => [primaryKey({ columns: [t.portalId, t.brandId, t.page, t.day] })],
);

/**
 * A host name this server answers for, other than APP_URL's: an
 * organization's own, added in its settings. Proved by a TXT record holding
 * `token` (lib/portal.ts challengeName), and pointing at the server when it
 * says where (DOMAIN_TARGET), before anything is served at it or a TLS
 * certificate is asked for it (GET /api/v1/domains/check). One serves the
 * app, the `primary` one being where links in email point, or one portal.
 */
export const domains = pgTable("domains", {
  host: text("host").primaryKey(),
  organizationId: uuid("organization_id")
    .notNull()
    .references(() => organizations.id, { onDelete: "cascade" }),
  /** The portal it serves; null: the app. Deleting the portal gives it back to the app. */
  portalId: uuid("portal_id").references(() => portals.id, { onDelete: "set null" }),
  /** Used for the app: the whole app answers here. Off when verified; any number of them. */
  app: boolean("app").notNull().default(false),
  /** Of those used for the app, where links in email point. One per organization. */
  primary: boolean("primary").notNull().default(false),
  token: text("token").notNull(),
  verifiedAt: timestamp("verified_at", { withTimezone: true }),
  /** When a verified one's TXT record was last looked at again (lib/core/reproof.ts). */
  checkedAt: timestamp("checked_at", { withTimezone: true }),
  /** Since when that record has been gone, at every look; null while it is there. */
  missingSince: timestamp("missing_since", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("domains_portal_unique").on(t.portalId),
  uniqueIndex("domains_primary_unique").on(t.organizationId).where(sql`${t.primary}`),
]);

/**
 * A domain the organization's people have their email at, proved by a TXT
 * record on the domain itself (lib/core/email-domains.ts). Not a custom
 * domain: it serves nothing. Single sign-on picks one; with `join`, anyone
 * whose address is at exactly it may join, able to read its workspace.
 */
export const emailDomains = pgTable("email_domains", {
  domain: text("domain").primaryKey(),
  organizationId: uuid("organization_id")
    .notNull()
    .references(() => organizations.id, { onDelete: "cascade" }),
  token: text("token").notNull(),
  verifiedAt: timestamp("verified_at", { withTimezone: true }),
  /** When a verified one's TXT record was last looked at again (lib/core/reproof.ts). */
  checkedAt: timestamp("checked_at", { withTimezone: true }),
  /** Since when that record has been gone, at every look; null while it is there. */
  missingSince: timestamp("missing_since", { withTimezone: true }),
  join: boolean("join").notNull().default(false),
  /** Where whoever joins by it lands, able to read: null for the organization's oldest workspace. */
  workspaceId: uuid("workspace_id").references(() => workspaces.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("email_domains_org_idx").on(t.organizationId)]);

/**
 * A GitHub account an organization says is its own (lib/core/hub-trust.ts),
 * proved like a domain: a file in its `.github` repository holding `token`.
 * Once proved, BrandHub names it beside a verified domain.
 */
export const githubOrgs = pgTable("github_orgs", {
  /** The account's login, lowercased: rust-lang. */
  login: text("login").primaryKey(),
  organizationId: uuid("organization_id")
    .notNull()
    .references(() => organizations.id, { onDelete: "cascade" }),
  token: text("token").notNull(),
  verifiedAt: timestamp("verified_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export type HubReportKind = "report" | "claim";

/**
 * What someone said about a public BrandHub listing (lib/core/hub-trust.ts):
 * a report, from anyone, or a claim, from an organization that proved a
 * domain or a GitHub account. For the listing's organization's admins
 * (Settings, BrandHub) and whoever runs the server, never shown publicly.
 * No IP address is kept.
 */
export const hubReports = pgTable(
  "hub_reports",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    kind: text("kind").$type<HubReportKind>().notNull(),
    /** A report's reason (lib/schemas.ts HubReportInput); a claim's is `claim`. */
    reason: text("reason").notNull(),
    note: text("note"),
    /** How to reach whoever sent it, as they gave it: a report's optional contact, a claimant's email. */
    contact: text("contact"),
    /** A claim's organization, and what it proved it holds when it claimed. */
    claimantId: uuid("claimant_id").references(() => organizations.id, { onDelete: "set null" }),
    proof: text("proof"),
    status: text("status").$type<"open" | "resolved">().notNull().default("open"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("hub_reports_brand_idx").on(t.brandId, t.createdAt.desc()),
    check("hub_reports_kind_check", sql`${t.kind} in ('report', 'claim')`),
    check("hub_reports_status_check", sql`${t.status} in ('open', 'resolved')`),
  ],
);

/**
 * Who starred which BrandHub brand (lib/core/hub.ts): the hub's Starred tab,
 * and the count on its Star button. A person, never a key. Named for when
 * starring was called following.
 */
export const hubStars = pgTable(
  "hub_follows",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.brandId] }), index("hub_follows_brand_idx").on(t.brandId)],
);

/** Who follows which BrandHub organization (lib/core/hub.ts): its brands show in the hub's Following tab. A person, never a key. */
export const hubOrgFollows = pgTable(
  "hub_org_follows",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.organizationId] }), index("hub_org_follows_org_idx").on(t.organizationId)],
);

/**
 * A listing an organization was offered, having proved its domain, and said
 * isn't its brand (lib/core/hub-claims.ts): the offer is no longer made.
 */
export const hubOffersRefused = pgTable(
  "hub_offers_refused",
  {
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.organizationId, t.brandId] })],
);

/**
 * An organization a person was offered to join by their email's domain, and
 * said not now to (lib/core/email-domains.ts): the offer is no longer made.
 */
export const joinOffersRefused = pgTable(
  "join_offers_refused",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.organizationId] })],
);

/**
 * Curated collections on BrandHub's front page ("Open-source project
 * brands"), set by whoever runs the server, in the database (docs: portals,
 * BrandHub): each lists public brands as {org}/{brand}, in order.
 */
export const hubCollections = pgTable("hub_collections", {
  slug: text("slug").primaryKey(),
  title: text("title").notNull(),
  description: text("description"),
  /** Where it shows among the others, lowest first. */
  position: integer("position").notNull().default(0),
  /** Its brands, as {org}/{brand}: one that isn't public is left out. */
  brands: text("brands").array().notNull().default(sql`'{}'::text[]`),
});

/**
 * This database, one row: its id marks the bucket as swept by it
 * (lib/bucket-owners.ts), so a second database on the same bucket is noticed
 * before either sweeps the other's files. Survives a dump and restore.
 */
export const instance = pgTable("instance", {
  singleton: boolean("singleton").primaryKey().default(true),
  id: uuid("id").notNull().defaultRandom(),
}, (t) => [check("instance_singleton_check", sql`${t.singleton}`)]);

/**
 * Renditions stored (lib/core/renditions.ts), so their bytes count toward the
 * organization's storage while the bucket keeps them (RENDITION_DAYS). The
 * workspace whose asset made it first; a rendition of the same bytes elsewhere
 * is the same object, counted once. Indexed by workspace and age: storage is
 * summed per organization on every upload and rendition (lib/core/usage.ts).
 */
export const renditions = pgTable("renditions", {
  key: text("key").primaryKey(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references(() => workspaces.id, { onDelete: "cascade" }),
  bytes: bigint("bytes", { mode: "number" }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index("renditions_workspace_created_idx").on(t.workspaceId, t.createdAt)]);

// ---- insights -----------------------------------------------------------------

/**
 * What happened, a row each, for Insights (lib/core/events.ts, PRD INS-1): a
 * file fetched, a use checked, a search, a BrandHub listing read. Appended
 * and never changed. Never an IP address, a person's name or a full URL:
 * who is a kind (lib/insights.ts) and an agent's key name; where from, only
 * the referrer's host. The customer's own data, in their own database:
 * nothing is sent anywhere. Kept EVENT_DAYS, then only its daily rollup.
 */
export const events = pgTable(
  "events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    /** The brand it was about: a hub listing's, a check's. */
    brandId: uuid("brand_id").references(() => brands.id, { onDelete: "cascade" }),
    kind: text("kind").$type<EventKind>().notNull(),
    surface: text("surface").$type<Surface>().notNull(),
    actor: text("actor").$type<Actor>().notNull(),
    /** An agent's key name ("Claude Code"); never a person's. */
    client: text("client"),
    assetId: uuid("asset_id").references(() => assets.id, { onDelete: "cascade" }),
    /** What else it was about: a search's words, a hub file, a check's context, a rule's key. */
    subject: text("subject"),
    /** The asset's version in its stack, or the brand release a hub file came from. */
    version: integer("version"),
    /** How it came out: a check's `allowed` or `refused`, a search's `found` or `empty`, a fetch's `current` or `superseded` version. */
    verdict: text("verdict"),
    /** A refused check's blocking reasons (lib/rights.ts codes). */
    reasons: text("reasons").array(),
    /** The assets a refused check offered instead. */
    offered: uuid("offered").array(),
    referrer: text("referrer"),
    day: date("day", { mode: "string" })
      .notNull()
      .default(sql`(now() at time zone 'utc')::date`),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("events_workspace_day_idx").on(t.workspaceId, t.day),
    index("events_asset_idx").on(t.assetId, t.at.desc()),
    // BrandHub's pull counts, across workspaces (lib/core/events.ts pullCounts): only events about a brand.
    index("events_brand_day_idx").on(t.brandId, t.day).where(sql`${t.brandId} is not null`),
    // The days the rollup reads and drops.
    index("events_day_idx").on(t.day),
    check("events_kind_check", sql`${t.kind} in ('fetch', 'check', 'search', 'view', 'pull', 'lookup', 'tool')`),
    check("events_actor_check", sql`${t.actor} in ('person', 'agent', 'anonymous')`),
  ],
);

/**
 * Events counted per day and everything they say but the moment and the
 * offer, rolled up from `events` once a day is over (lib/core/events.ts
 * rollUp), and kept after the raw rows go, for ROLLUP_DAYS (lib/insights.ts).
 */
const counted = {
  workspaceId: uuid("workspace_id").notNull(),
  brandId: uuid("brand_id"),
  day: date("day", { mode: "string" }).notNull(),
  kind: text("kind").$type<EventKind>().notNull(),
  surface: text("surface").$type<Surface>().notNull(),
  actor: text("actor").$type<Actor>().notNull(),
  client: text("client"),
  assetId: uuid("asset_id"),
  subject: text("subject"),
  version: integer("version"),
  verdict: text("verdict"),
  reasons: text("reasons").array(),
  referrer: text("referrer"),
  count: integer("count").notNull(),
};

export const eventDays = pgTable(
  "event_days",
  {
    ...counted,
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    brandId: uuid("brand_id").references(() => brands.id, { onDelete: "cascade" }),
    assetId: uuid("asset_id").references(() => assets.id, { onDelete: "cascade" }),
  },
  (t) => [
    index("event_days_workspace_day_idx").on(t.workspaceId, t.day),
    index("event_days_asset_idx").on(t.assetId),
    index("event_days_day_idx").on(t.day),
    index("event_days_brand_day_idx").on(t.brandId, t.day).where(sql`${t.brandId} is not null`),
  ],
);

const DIMS = sql.raw("workspace_id, brand_id, day, kind, surface, actor, client, asset_id, subject, version, verdict, reasons, referrer");

/**
 * What every chart reads: the rollup, and the raw events of the days not
 * rolled up yet, counted the same way. Always current, whenever the rollup
 * last ran.
 */
export const eventCounts = pgView("event_counts", counted).as(
  sql`select ${DIMS}, count from ${eventDays}
    union all
    select ${DIMS}, count(*)::int from ${events}
    where day > coalesce((select max(day) from ${eventDays}), '-infinity'::date)
    group by ${DIMS}`,
);

// ---- the catalog ----------------------------------------------------------------

/** A name as an address segment: "Press kit" is press-kit. lib/catalog.ts slugOf, as SQL. */
const slugSql = (name: string) => sql.raw(`trim(both '-' from regexp_replace(lower(${name}), '[^a-z0-9]+', '-', 'g'))`);

/**
 * Every object a person or an agent can find, in one shape (lib/core/catalog.ts,
 * PRD: Artbucket Catalog): assets, collections, brands and portals, and the
 * parts of a brand (its rules and pages), each with its workspace, an address
 * segment (`slug`), a status on one lifecycle (lib/catalog.ts STATUSES) and a
 * search vector. A view, so nothing is written twice; an asset's vector is its
 * indexed column, the rest are small enough to read as they are.
 *
 * ponytail: an asset's slug comes from its filename, so two files named alike
 * share one and an address picks the newest; store a unique slug if that bites.
 */
export const catalogObjects = pgView("catalog_objects", {
  id: uuid("id").notNull(),
  type: text("type").$type<"asset" | "collection" | "brand" | "portal" | "rule" | "page">().notNull(),
  workspaceId: uuid("workspace_id").notNull(),
  /** A part's object: a rule's or a page's brand. */
  parentId: uuid("parent_id"),
  slug: text("slug").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  status: text("status").$type<"draft" | "in_review" | "current" | "replaced" | "archived">().notNull(),
  /** An asset's version in its stack, a brand's latest release. */
  release: integer("release"),
  /** The last day an asset may be used (lib/rights.ts). */
  expires: text("expires"),
  /** Only grants on it reach it (lib/access.ts): an asset's own flag, or every collection it is in. */
  private: boolean("private").notNull(),
  /** An asset's collections. */
  collections: uuid("collections").array().notNull(),
  tags: jsonb("tags").$type<string[]>().notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
  search: tsvector("search").notNull(),
}).as(
  sql`select a.id, 'asset' as type, a.workspace_id, null::uuid as parent_id,
      coalesce(nullif(${slugSql("regexp_replace(a.filename, '\\.[^.]*$', '')")}, ''), a.id::text) as slug,
      a.filename as name, a.metadata ->> 'description' as description,
      case when a.status = 'draft' then 'draft' when a.status = 'proposed' then 'in_review'
        when a.status in ('archived', 'rejected') then 'archived'
        when a.superseded_by is not null or (a.stack_id is not null and not a.current) then 'replaced'
        else 'current' end as status,
      a.version as release, a.rights ->> 'expires' as expires,
      (a.private or (exists (select 1 from ${collectionAssets} ca where ca.asset_id = a.id)
        and not exists (select 1 from ${collectionAssets} ca join ${collections} c on c.id = ca.collection_id where ca.asset_id = a.id and not c.private))) as private,
      coalesce((select array_agg(ca.collection_id) from ${collectionAssets} ca where ca.asset_id = a.id), '{}'::uuid[]) as collections,
      a.tags, a.created_at, a.updated_at, a.search
    from ${assets} a where a.deleted_at is null
    union all
    select c.id, 'collection', c.workspace_id, null, ${slugSql("c.name")}, c.name, null, 'current', null, null, c.private, '{}'::uuid[], '[]'::jsonb,
      c.created_at, c.created_at, to_tsvector('simple', c.name)
    from ${collections} c
    union all
    select b.id, 'brand', b.workspace_id, null, b.slug, b.name, null,
      case when r.number is null then 'draft' else 'current' end, r.number, null, false, '{}'::uuid[], '[]'::jsonb,
      b.created_at, coalesce(u.at, b.created_at), to_tsvector('simple', b.name || ' ' || b.slug || ' ' || coalesce(b.domain, ''))
    from ${brands} b
    left join lateral (select max(v.number) as number from ${brandVersions} v where v.brand_id = b.id and v.published_at is not null) r on true
    left join lateral (select max(v.updated_at) as at from ${brandVersions} v where v.brand_id = b.id) u on true
    union all
    select p.id, 'portal', p.workspace_id, null, p.slug, p.name, p.intro,
      case when p.expires_at < now() then 'archived' else 'current' end, null, null, false, '{}'::uuid[], '[]'::jsonb,
      p.created_at, p.updated_at, to_tsvector('simple', p.name || ' ' || p.slug || ' ' || coalesce(p.intro, ''))
    from ${portals} p
    union all
    select r.id, 'rule', b.workspace_id, b.id, r.key, coalesce(r.label, r.key), r.usage, 'current', null, null, false, '{}'::uuid[], '[]'::jsonb,
      r.created_at, r.updated_at, to_tsvector('simple', regexp_replace(r.key, '[._-]+', ' ', 'g') || ' ' || coalesce(r.label, '') || ' ' || coalesce(r.usage, ''))
    from ${brandRules} r join ${brands} b on b.id = r.brand_id where r.context is null
    union all
    select g.id, 'page', b.workspace_id, b.id, g.slug, g.title, g.lede, 'current', null, null, false, '{}'::uuid[], '[]'::jsonb,
      g.created_at, g.updated_at, to_tsvector('simple', g.title || ' ' || coalesce(g.eyebrow, '') || ' ' || coalesce(g.lede, ''))
    from ${brandPages} g join ${brands} b on b.id = g.brand_id`,
);

/**
 * What uses what, upstream to downstream (lib/core/catalog.ts lineage), from
 * links the tables already hold: an asset to what replaced it and to what was
 * made from it, to the brands whose rules name it (`via`: their keys) and the
 * collections it is in; a collection or a brand to the portals that offer it;
 * a brand to the brands forked from it.
 */
export const catalogEdges = pgView("catalog_edges", {
  fromId: uuid("from_id").notNull(),
  toId: uuid("to_id").notNull(),
  kind: text("kind").$type<"replaced_by" | "derived" | "rule" | "member" | "offered" | "fork">().notNull(),
  via: text("via"),
}).as(
  sql`select a.id as from_id, a.superseded_by as to_id, 'replaced_by' as kind, null as via from ${assets} a where a.superseded_by is not null
    union all
    select a.parent_asset_id, a.id, 'derived', null from ${assets} a where a.parent_asset_id is not null
    union all
    select bra.asset_id, r.brand_id, 'rule', string_agg(distinct r.key, ', ') from ${brandRuleAssets} bra join ${brandRules} r on r.id = bra.rule_id group by bra.asset_id, r.brand_id
    union all
    select ca.asset_id, ca.collection_id, 'member', null from ${collectionAssets} ca
    union all
    select pc.collection_id, pc.portal_id, 'offered', null from ${portalCollections} pc
    union all
    select pb.brand_id, pb.portal_id, 'offered', null from ${portalBrands} pb
    union all
    select s.id, b.id, 'fork', b.forked_from from ${brands} b
      join ${organizations} o on o.slug = split_part(b.forked_from, '/', 1)
      join ${workspaces} w on w.organization_id = o.id
      join ${brands} s on s.workspace_id = w.id and s.slug = split_part(split_part(b.forked_from, '/', 2), '@', 1)
    where b.forked_from is not null`,
);
