import { relations, sql } from "drizzle-orm";
import {
  type AnyPgColumn,
  bigint,
  boolean,
  date,
  check,
  customType,
  index,
  primaryKey,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import type { C2pa } from "@/lib/c2pa";
import type { FieldType, FieldValues } from "@/lib/fields";
import type { Metadata } from "@/lib/metadata";
import type { ThemeSettings } from "@/lib/brand-theme";
import type { CollectionIcon } from "@/lib/collection-icons";
import type { SnapRule, VersionKind } from "@/lib/history";
import type { Audience, PageLayout, PageText, Section, SnapPage } from "@/lib/pages";
import type { Origin, Rights } from "@/lib/rights";
import type { RuleSpec, RuleType, RuleValue } from "@/lib/rules";
import type { Scope } from "@/lib/scopes";
import type { Ability, Resource } from "@/lib/access";
import type { Status } from "@/lib/lifecycle";
import type { PortalAccess, PortalPreset, PortalSite, PortalTheme } from "@/lib/portal";

export type AssetStatus = Status;

const tsvector = customType<{ data: string }>({ dataType: () => "tsvector" });

/**
 * Assets are content-addressed: `sha256` is the identity of the bytes, and the
 * storage key is derived from it. Uploading the same file twice is a no-op.
 *
 */
export const assets = pgTable(
  "assets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
    /** Unique within a workspace. Storage is keyed by it alone, so workspaces share identical bytes. */
    sha256: text("sha256").notNull(),
    filename: text("filename").notNull(),
    mime: text("mime").notNull(),
    size: integer("size").notNull(),
    /** Only people with a grant on it (or a collection it is in) and admins see it (lib/access.ts). */
    private: boolean("private").notNull().default(false),
    /**
     * Served at /a/{id} to anyone, for embedding, while it may be used
     * (lib/lifecycle.ts). Otherwise only people who can see it, and holders of
     * a signed URL (lib/signed.ts), get the bytes.
     */
    public: boolean("public").notNull().default(false),
    width: integer("width"),
    height: integer("height"),
    /** Freeform probe output (format, pages, colour space). */
    probe: jsonb("probe").$type<Record<string, unknown>>(),
    /** EXIF / IPTC / XMP read from the file on ingest. See lib/metadata.ts. */
    metadata: jsonb("metadata").$type<Metadata>(),
    /** Lowercased and deduped by lib/tags.ts before they get here. */
    tags: jsonb("tags").$type<string[]>().notNull().default([]),
    /** Values for the library's custom fields, keyed by `fields.key`. */
    fields: jsonb("fields").$type<FieldValues>().notNull().default({}),
    /**
     * Values this asset inherits from its collections, materialized by
     * lib/core/collections.ts whenever membership or a collection changes, so
     * search and filters read one row. The asset's own `fields` win over these.
     */
    inherited: jsonb("inherited").$type<FieldValues>().notNull().default({}),
    /**
     * Where it is in its lifecycle (lib/lifecycle.ts): `draft`, `proposed` (in
     * review) until a human promotes it, which is what a propose-scoped key (an
     * agent) uploads, `active` (approved), `archived`, `rejected`. Expired is
     * derived from `rights`. Default searches show approved, unexpired assets.
     */
    status: text("status").$type<AssetStatus>().notNull().default("active"),
    /**
     * Who proposed it: the API key's name, or "web". Kept after review, so a
     * person sees who sent what and an agent can find its own proposals.
     */
    proposedBy: text("proposed_by"),
    /**
     * Why a person rejected it. A rejected asset is kept, out of the library
     * and the review queue, so the agent that proposed it can read the reason.
     */
    reviewNote: text("review_note"),
    /** Tags an agent suggested, waiting for a human to accept or dismiss. */
    proposedTags: jsonb("proposed_tags").$type<string[]>().notNull().default([]),
    /** Custom field values an agent suggested, keyed like `fields`, waiting for a human to accept or dismiss. */
    proposedFields: jsonb("proposed_fields").$type<FieldValues>().notNull().default({}),
    /** License, territories, channels, embargo, expiry, model release (lib/rights.ts); null says nothing. */
    rights: jsonb("rights").$type<Rights>(),
    /** How it came to be: shot, licensed, or generated by a model. */
    origin: text("origin").$type<Origin>(),
    /** What it was made from: the photo an edit started from, the image a model was given. */
    parentAssetId: uuid("parent_asset_id").references((): AnyPgColumn => assets.id, { onDelete: "set null" }),
    /** The tool or model that made it, e.g. "gpt-image 2.0". */
    generator: text("generator"),
    prompt: text("prompt"),
    /** C2PA Content Credentials read on ingest (lib/c2pa.ts); the original keeps the manifest itself. */
    c2pa: jsonb("c2pa").$type<C2pa>(),
    /** The asset that replaces this one. /api/v1/check refuses a replaced asset and names this. */
    supersededBy: uuid("superseded_by").references((): AnyPgColumn => assets.id, { onDelete: "set null" }),
    /**
     * Versions of one thing share a stack: the id of the asset it started
     * from, kept as a plain value so the stack outlives that asset. Null for
     * an asset with one version (lib/core/versions.ts).
     */
    stackId: uuid("stack_id"),
    /** 1, 2, 3 within the stack. */
    version: integer("version"),
    /**
     * The stack's current approved version: the one the library shows, share
     * links serve, and every other approved version is superseded by.
     */
    current: boolean("current").notNull().default(false),
    /**
     * Deleted, and restorable until lib/core/sweep.ts purges it 30 days on.
     * Its bytes stay until then; it reads `state: "deleted"` and is served to nobody.
     */
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    /**
     * Maintained by Postgres, so it cannot drift from the columns it indexes.
     * 'simple' rather than 'english': asset search is names and keywords, where
     * stemming "logos" to "logo" matters less than matching "fox_v3" by "fox".
     * Filenames are split on . _ - first, since the parser keeps "fox_v3.png"
     * as one token.
     */
    search: tsvector("search")
      .notNull()
      .generatedAlwaysAs(
        sql`setweight(to_tsvector('simple', regexp_replace(filename, '[._-]+', ' ', 'g')), 'A') || setweight(to_tsvector('simple', tags), 'A') || setweight(jsonb_to_tsvector('simple', coalesce(metadata, '{}'), '["string"]'), 'B') || setweight(jsonb_to_tsvector('simple', fields || inherited, '["string"]'), 'B')`,
      ),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    unique("assets_workspace_sha256_unique").on(t.workspaceId, t.sha256),
    index("assets_workspace_created_at_idx").on(t.workspaceId, t.createdAt.desc()),
    // Whether anything still holds some bytes, across workspaces: the sweeper asks.
    index("assets_sha256_idx").on(t.sha256),
    index("assets_deleted_at_idx").on(t.deletedAt).where(sql`${t.deletedAt} is not null`),
    index("assets_search_idx").using("gin", t.search),
    index("assets_tags_idx").using("gin", sql`${t.tags} jsonb_path_ops`),
    // Field filters match the effective value, own over inherited: `inherited || fields`.
    index("assets_effective_fields_idx").using("gin", sql`(${t.inherited} || ${t.fields}) jsonb_path_ops`),
    check("assets_status_check", sql`${t.status} in ('draft', 'proposed', 'active', 'archived', 'rejected')`),
    index("assets_proposed_by_idx").on(t.proposedBy),
    check("assets_origin_check", sql`${t.origin} in ('shot', 'licensed', 'generated')`),
    check("assets_not_superseded_by_self", sql`${t.supersededBy} <> ${t.id}`),
    unique("assets_stack_version_unique").on(t.stackId, t.version),
    uniqueIndex("assets_one_current").on(t.stackId).where(sql`${t.current}`),
    check("assets_stacked_check", sql`(${t.stackId} is null) = (${t.version} is null)`),
  ],
);

export type Asset = typeof assets.$inferSelect;
export type NewAsset = typeof assets.$inferInsert;

/** A named set of assets that can carry field values its members inherit. */
export const collections = pgTable("collections", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  /** A Tabler icon name from lib/collection-icons.ts; null shows a folder. */
  icon: text("icon"),
  fields: jsonb("fields").$type<FieldValues>().notNull().default({}),
  /** Only people with a grant on it and admins see it; assets in private collections only are private too. */
  private: boolean("private").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .default(sql`now()`),
});

export const collectionAssets = pgTable(
  "collection_assets",
  {
    collectionId: uuid("collection_id")
      .notNull()
      .references(() => collections.id, { onDelete: "cascade" }),
    assetId: uuid("asset_id")
      .notNull()
      .references(() => assets.id, { onDelete: "cascade" }),
  },
  (t) => [
    primaryKey({ columns: [t.collectionId, t.assetId] }),
    // The primary key serves "members of a collection"; this serves "collections of an asset".
    index("collection_assets_asset_idx").on(t.assetId),
  ],
);

/**
 * A workspace's custom field schema. `key` is the identity: it is what asset
 * values are stored under, so it and `type` never change once created. Make a
 * new field instead.
 */
export const fields = pgTable(
  "fields",
  {
  workspaceId: uuid("workspace_id")
    .notNull()
    .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
  key: text("key").notNull(),
  label: text("label").notNull(),
  type: text("type").$type<FieldType>().notNull(),
  options: jsonb("options").$type<string[]>().notNull().default([]),
  required: boolean("required").notNull().default(false),
  position: integer("position").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .default(sql`now()`),
  },
  (t) => [
    primaryKey({ columns: [t.workspaceId, t.key] }),
    check("fields_type_check", sql`${t.type} in ('text', 'number', 'date', 'boolean', 'select')`),
  ],
);

/**
 * A named query. `query` is the /api/v1/assets query string, validated when
 * saved, so running one is a plain GET any client can make.
 */
export const savedSearches = pgTable("saved_searches", {
  id: uuid("id").primaryKey().defaultRandom(),
  workspaceId: uuid("workspace_id")
    .notNull()
    .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  query: text("query").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .default(sql`now()`),
});

/**
 * API keys, one workspace each. Only a SHA-256 of the secret is stored: keys
 * are 256 random bits, so a fast hash is enough and a leaked table leaks no usable key. `prefix`
 * is the first characters of the secret, to tell keys apart in a list.
 */
export const apiKeys = pgTable(
  "api_keys",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /** A key works in one workspace, with one scope there. */
    workspaceId: uuid("workspace_id")
      .notNull()
      .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    prefix: text("prefix").notNull(),
    hash: text("hash").notNull().unique(),
    scope: text("scope").$type<Scope>().notNull(),
    /**
     * Whose agent this is, for a key minted by OAuth or `artbucket login`
     * (lib/core/oauth.ts): it can never do more than they can, and goes
     * with them. Null for a key an admin made, which answers to nobody.
     */
    userId: text("user_id").references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
    /** Bumped on every request that presents it: "Connected agents" and "waiting for first call". */
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
    calls: integer("calls").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [check("api_keys_scope_check", sql`${t.scope} in ('read', 'propose', 'write', 'admin')`)],
);

/**
 * A brand: its own rules and its own history. Exactly one per workspace is the default,
 * which is what /brand and an unqualified /api/v1/brand/rules mean.
 */
export const brands = pgTable(
  "brands",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    isDefault: boolean("is_default").notNull().default(false),
    /** How its pages look (lib/brand-theme.ts ThemeSettings): only what was set, the rest read from the rules. */
    theme: jsonb("theme").$type<ThemeSettings>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    unique("brands_workspace_slug_unique").on(t.workspaceId, t.slug),
    uniqueIndex("brands_one_default").on(t.workspaceId).where(sql`${t.isDefault}`),
  ],
);

/**
 * The canon: one brand rule per (brand, key, context). A null context is the default;
 * see lib/rules.ts for how a context resolves. `value` is checked against
 * `type` by lib/rules.ts, and `type` never changes: delete and recreate.
 */
export const brandRules = pgTable(
  "brand_rules",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    key: text("key").notNull(),
    context: text("context"),
    type: text("type").$type<RuleType>().notNull(),
    /** The heading readers see; null reads the key in words. Keys never change with it. */
    label: text("label"),
    value: jsonb("value").$type<RuleValue>().notNull(),
    /** Details beyond the value, checked against `type` (lib/rules.ts RULE_SPEC). */
    spec: jsonb("spec").$type<RuleSpec>(),
    usage: text("usage"),
    /** Order on the page. Shared by a key's context versions, so they move together. */
    position: integer("position").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    unique("brand_rules_brand_key_context_unique").on(t.brandId, t.key, t.context).nullsNotDistinct(),
    check("brand_rules_type_check", sql`${t.type} in ('color', 'text', 'number', 'list', 'font')`),
  ],
);

/**
 * Assets a rule points at, in order: the logo it governs, examples of doing it
 * right. Real foreign keys, so deleting an asset drops it from every rule.
 */
export const brandRuleAssets = pgTable(
  "brand_rule_assets",
  {
    ruleId: uuid("rule_id")
      .notNull()
      .references(() => brandRules.id, { onDelete: "cascade" }),
    assetId: uuid("asset_id")
      .notNull()
      .references(() => assets.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
    /** A rendition spec (lib/transform.ts), e.g. w_512,f_png: the rule means this size, not the original. */
    rendition: text("rendition"),
  },
  (t) => [primaryKey({ columns: [t.ruleId, t.assetId] }), index("brand_rule_assets_asset_idx").on(t.assetId)],
);

/**
 * A brand's history: the whole rule set after each change (lib/history.ts).
 * Edits close together by the same actor extend the latest version instead of
 * starting one, so the list reads like a doc's, not like a keystroke log.
 */
export const brandVersions = pgTable(
  "brand_versions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    /** 1, 2, 3 within the brand. */
    number: integer("number").notNull(),
    kind: text("kind").$type<VersionKind>().notNull(),
    /** Set by a person to keep a version as a checkpoint; named versions are never extended. */
    name: text("name"),
    /** Who made it: an API key's name, or "web" for the app without a key. */
    actor: text("actor").notNull(),
    /** For a restore: the version it put back. */
    restoredFrom: integer("restored_from"),
    /** Keys touched, in order, for the one-line summary. */
    changed: jsonb("changed").$type<string[]>().notNull().default([]),
    snapshot: jsonb("snapshot").$type<SnapRule[]>().notNull(),
    /** The brand's pages as they stood; null in versions from before pages, which a restore leaves alone. */
    pages: jsonb("pages").$type<SnapPage[]>(),
    /** The brand's theme settings; null in versions from before themes, which a restore leaves alone. */
    theme: jsonb("theme").$type<ThemeSettings>(),
    /** Set when this version was published: portals show it, and later edits start a new version. */
    publishedAt: timestamp("published_at", { withTimezone: true }),
    publishedBy: text("published_by"),
    /** What the publish said, for readers' "what's new", and a picture with it. */
    note: text("note"),
    noteImage: uuid("note_image"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    unique("brand_versions_brand_number_unique").on(t.brandId, t.number),
    check("brand_versions_kind_check", sql`${t.kind} in ('baseline', 'edit', 'restore')`),
  ],
);

/**
 * A brand's pages: guidelines laid out for people, over its rules
 * (lib/pages.ts). Sections are stored whole, in order, since a page is always
 * read and written whole; they bind rules by key, never by value.
 */
export const brandPages = pgTable(
  "brand_pages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    slug: text("slug").notNull(),
    title: text("title").notNull(),
    position: integer("position").notNull().default(0),
    hidden: boolean("hidden").notNull().default(false),
    sections: jsonb("sections").$type<Section[]>().notNull().default([]),
    /** The page it sits under, by slug: ids change on every restore (core/page-store.ts writePages). */
    parent: text("parent"),
    eyebrow: text("eyebrow"),
    lede: text("lede"),
    /** No foreign key: a restored snapshot can name an asset purged since, and reads leave it out. */
    cover: uuid("cover"),
    icon: text("icon").$type<CollectionIcon>(),
    audience: text("audience").$type<Audience>().notNull().default("everyone"),
    tabs: boolean("tabs").notNull().default(false),
    /** Slugs it had before a rename, so old links keep working. */
    aliases: text("aliases").array().notNull().default(sql`'{}'::text[]`),
    /** Its title, eyebrow and lede in other languages, by language tag; null for none. */
    translations: jsonb("translations").$type<Record<string, PageText>>(),
    layout: text("layout").$type<PageLayout>().notNull().default("book"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    /** The last change to what it says, not to where it sits. */
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    unique("brand_pages_brand_slug_unique").on(t.brandId, t.slug),
    check("brand_pages_audience_check", sql`${t.audience} in ('everyone', 'partners', 'members')`),
    check("brand_pages_layout_check", sql`${t.layout} in ('book', 'landing')`),
  ],
);

export type ActivityVerb =
  | "added"
  | "suggested"
  | "approved"
  | "rejected"
  | "deleted"
  | "suggested_tags"
  | "suggested_fields"
  | "archived"
  | "unarchived"
  | "made_current"
  | "restored";

/**
 * What happened to assets, and who did it: a person by name, an API key by
 * name, a share link's guest, or "web" for the app without an account. Brand rule changes are not here: brand_versions already
 * keeps them, and /api/v1/activity reads both. `assetId` is not a foreign
 * key: an asset's history outlives the asset.
 */
export const activity = pgTable(
  "activity",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references((): AnyPgColumn => workspaces.id, { onDelete: "cascade" }),
    at: timestamp("at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    actor: text("actor").notNull(),
    /** Done with an API key: an agent or a script, not a person in the app. */
    agent: boolean("agent").notNull().default(false),
    verb: text("verb").$type<ActivityVerb>().notNull(),
    assetId: uuid("asset_id"),
    /** The asset's title or filename when it happened, so a deleted one still reads. */
    label: text("label").notNull(),
    /** Suggested tags or fields, a rejection's reason, the version it is. */
    detail: jsonb("detail").$type<{ tags?: string[]; fields?: string[]; note?: string; version?: number }>(),
  },
  (t) => [index("activity_workspace_at_idx").on(t.workspaceId, t.at.desc())],
);

// ---- people -----------------------------------------------------------------

/**
 * Accounts, as better-auth keeps them (lib/auth.ts): who someone is. What they
 * may do is `grants`, which is ours.
 */
export const users = pgTable("users", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const sessions = pgTable(
  "sessions",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    token: text("token").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("sessions_user_idx").on(t.userId)],
);

/** A way to sign in: a password (`providerId` "credential") or an OIDC identity. */
export const accounts = pgTable(
  "accounts",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("accounts_user_idx").on(t.userId)],
);

/**
 * So better-auth reads a session with its person, or a person with their
 * ways to sign in, in one query rather than two (lib/auth.ts `joins`).
 */
export const usersRelations = relations(users, ({ many }) => ({ sessions: many(sessions), accounts: many(accounts) }));
export const sessionsRelations = relations(sessions, ({ one }) => ({ user: one(users, { fields: [sessions.userId], references: [users.id] }) }));
export const accountsRelations = relations(accounts, ({ one }) => ({ user: one(users, { fields: [accounts.userId], references: [users.id] }) }));

/**
 * OAuth clients that registered themselves (RFC 7591): Claude, ChatGPT, the
 * CLI. Public clients, no secret: PKCE stands in for one. What a client is
 * granted is an API key (lib/core/oauth.ts), so this is only its name and
 * where it may be sent back to.
 */
export const oauthClients = pgTable("oauth_clients", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  redirectUris: jsonb("redirect_uris").$type<string[]>().notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** better-auth's, and ours for OAuth codes waiting to be exchanged (lib/core/oauth.ts). */
export const verifications = pgTable("verifications", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---- tenancy and access -----------------------------------------------------

/** A team, or a client of an agency: people, and the workspaces they share. */
export const organizations = pgTable("organizations", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * A library: its own assets, collections, fields, brands, searches and keys.
 * Nothing crosses from one workspace to another but the stored bytes.
 */
export const workspaces = pgTable(
  "workspaces",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique("workspaces_org_slug_unique").on(t.organizationId, t.slug)],
);

/**
 * What a person may do, and where: a scope (lib/scopes.ts) on an
 * organization, a workspace, a collection or one asset. Grants add up and
 * reach down: admin on the organization is admin in every workspace, write on
 * a collection is write on its assets (lib/access.ts). Having one is being a
 * member. `resourceId` names the thing; it is not a foreign key, so core
 * deletes a collection's or an asset's grants with it.
 */
export const grants = pgTable(
  "grants",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    /** Null for a grant on the organization itself. */
    workspaceId: uuid("workspace_id").references(() => workspaces.id, { onDelete: "cascade" }),
    resource: text("resource").$type<Resource>().notNull(),
    resourceId: uuid("resource_id").notNull(),
    scope: text("scope").$type<Scope>().notNull(),
    /** Abilities the scope would give that this grant doesn't: an editor who can't delete (lib/access.ts). */
    limits: jsonb("limits").$type<Ability[]>().notNull().default([]),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique("grants_user_resource_unique").on(t.userId, t.resource, t.resourceId),
    index("grants_org_idx").on(t.organizationId),
    check("grants_resource_check", sql`${t.resource} in ('organization', 'workspace', 'collection', 'asset')`),
    check("grants_scope_check", sql`${t.scope} in ('read', 'propose', 'write', 'admin')`),
    check("grants_workspace_check", sql`(${t.resource} = 'organization') = (${t.workspaceId} is null)`),
  ],
);

/**
 * A grant waiting for someone to take it. The link carries the token, found
 * by its hash; the token itself is kept sealed, so an admin can copy the
 * link again. `email` is who it was meant for.
 */
export const invitations = pgTable(
  "invitations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    workspaceId: uuid("workspace_id").references(() => workspaces.id, { onDelete: "cascade" }),
    email: text("email").notNull(),
    resource: text("resource").$type<Resource>().notNull(),
    resourceId: uuid("resource_id").notNull(),
    scope: text("scope").$type<Scope>().notNull(),
    limits: jsonb("limits").$type<Ability[]>().notNull().default([]),
    tokenHash: text("token_hash").notNull().unique(),
    /** The token again, sealed (lib/settings.ts seal), so an admin can copy the link later. Lookups use the hash. */
    tokenSealed: text("token_sealed"),
    invitedBy: text("invited_by").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    acceptedBy: text("accepted_by").references(() => users.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("invitations_org_idx").on(t.organizationId),
    check("invitations_scope_check", sql`${t.scope} in ('read', 'propose', 'write', 'admin')`),
  ],
);

export type ShareKind = "view" | "upload";

/**
 * A link for people without an account. `view` shows a collection or one
 * asset; `upload` takes files into a collection (or the workspace) as
 * proposals. The token is kept as is, so its maker can copy the link again:
 * a password (scrypt, lib/share.ts) is what protects one that matters.
 */
export const shareLinks = pgTable(
  "share_links",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    kind: text("kind").$type<ShareKind>().notNull(),
    collectionId: uuid("collection_id").references(() => collections.id, { onDelete: "cascade" }),
    assetId: uuid("asset_id").references(() => assets.id, { onDelete: "cascade" }),
    name: text("name"),
    token: text("token").notNull().unique(),
    passwordHash: text("password_hash"),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    createdBy: text("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("share_links_workspace_idx").on(t.workspaceId),
    check("share_links_kind_check", sql`${t.kind} in ('view', 'upload')`),
    check(
      "share_links_target_check",
      sql`(${t.kind} = 'view' and num_nonnulls(${t.collectionId}, ${t.assetId}) = 1) or (${t.kind} = 'upload' and ${t.assetId} is null)`,
    ),
  ],
);

/**
 * Who changed who may do what: sign-ins, members, grants, invitations, keys,
 * share links, workspaces. What happened to assets is `activity`; this is the
 * trail a security review reads. Rows outlive what they name.
 */
export const audit = pgTable(
  "audit",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
    /** Null for what belongs to a person, not an organization: signing in. */
    organizationId: uuid("organization_id"),
    workspaceId: uuid("workspace_id"),
    actor: text("actor").notNull(),
    userId: text("user_id"),
    keyId: uuid("key_id"),
    action: text("action").notNull(),
    /** What it was done to, as it read then: an email, a key's name, a collection. */
    target: text("target"),
    detail: jsonb("detail").$type<Record<string, unknown>>(),
    ip: text("ip"),
  },
  (t) => [index("audit_org_at_idx").on(t.organizationId, t.at.desc()), index("audit_user_idx").on(t.userId)],
);

/**
 * Settings (lib/settings.ts): one row per key and place, an organization's or
 * a workspace's. Secret properties are sealed before they get here.
 */
export const settings = pgTable(
  "settings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    /** Null for the organization's own. */
    workspaceId: uuid("workspace_id").references(() => workspaces.id, { onDelete: "cascade" }),
    key: text("key").notNull(),
    value: jsonb("value").$type<Record<string, unknown>>().notNull(),
    updatedBy: text("updated_by").notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique("settings_place_key_unique").on(t.organizationId, t.workspaceId, t.key).nullsNotDistinct()],
);

/**
 * Delivery traffic: what /a/{id} served, per workspace and day (lib/core/usage.ts).
 * Counted by the delivery route, read in Settings, Usage.
 */
export const traffic = pgTable(
  "traffic",
  {
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    day: date("day", { mode: "string" }).notNull(),
    requests: integer("requests").notNull().default(0),
    bytes: bigint("bytes", { mode: "number" }).notNull().default(0),
  },
  (t) => [primaryKey({ columns: [t.workspaceId, t.day] })],
);

// ---- portals ------------------------------------------------------------------

/**
 * A brand portal (lib/core/portals.ts): chosen collections and brands, themed, at
 * /p/{slug} or a domain of its own, for people outside the team. It shows
 * only approved, unexpired, current assets, and offers renditions made for a
 * purpose rather than raw originals. Who gets in: anyone (`public`), whoever
 * has the password, or people with access to the workspace (`members`); an
 * approved access request lets someone in either of the last two.
 */
export const portals = pgTable(
  "portals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    /** Its address: /p/{slug}. Unique on the server. */
    slug: text("slug").notNull().unique(),
    name: text("name").notNull(),
    /** A few paragraphs under the name: what this is, who it is for, who to ask. */
    intro: text("intro"),
    access: text("access").$type<PortalAccess>().notNull().default("public"),
    passwordHash: text("password_hash"),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    presets: jsonb("presets").$type<PortalPreset[]>().notNull().default(["web", "print", "social"]),
    theme: jsonb("theme").$type<PortalTheme>().notNull().default({ logo: null, accent: null, background: null }),
    /** The site around its pages: footer, quick grab, terms, and whether search engines may list it (lib/portal.ts PortalSite). */
    site: jsonb("site").$type<PortalSite>().notNull().default({}),
    createdBy: text("created_by").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("portals_workspace_idx").on(t.workspaceId),
    check("portals_access_check", sql`${t.access} in ('public', 'password', 'members')`),
    check("portals_password_check", sql`${t.access} <> 'password' or ${t.passwordHash} is not null`),
  ],
);

/** A portal's collections, in the order it shows them. Deleting a collection takes it off every portal. */
export const portalCollections = pgTable(
  "portal_collections",
  {
    portalId: uuid("portal_id")
      .notNull()
      .references(() => portals.id, { onDelete: "cascade" }),
    collectionId: uuid("collection_id")
      .notNull()
      .references(() => collections.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
  },
  (t) => [primaryKey({ columns: [t.portalId, t.collectionId] }), index("portal_collections_collection_idx").on(t.collectionId)],
);

/** A portal's brands, in the order its tabs show them: each brand's guidelines, read-only. Deleting a brand takes it off every portal. */
export const portalBrands = pgTable(
  "portal_brands",
  {
    portalId: uuid("portal_id")
      .notNull()
      .references(() => portals.id, { onDelete: "cascade" }),
    brandId: uuid("brand_id")
      .notNull()
      .references(() => brands.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
  },
  (t) => [primaryKey({ columns: [t.portalId, t.brandId] }), index("portal_brands_brand_idx").on(t.brandId)],
);

export type PortalRequestStatus = "pending" | "approved" | "denied";

/**
 * Someone outside asking into a portal that isn't public. Approved, they get
 * a key of their own, found by its hash and kept sealed so the link can be
 * copied again; it stops at `expiresAt` or when the request is deleted.
 */
export const portalRequests = pgTable(
  "portal_requests",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    portalId: uuid("portal_id")
      .notNull()
      .references(() => portals.id, { onDelete: "cascade" }),
    email: text("email").notNull(),
    name: text("name"),
    /** Who they are and what they need it for, in their words. */
    note: text("note"),
    status: text("status").$type<PortalRequestStatus>().notNull().default("pending"),
    keyHash: text("key_hash").unique(),
    keySealed: text("key_sealed"),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    decidedBy: text("decided_by"),
    decidedAt: timestamp("decided_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("portal_requests_portal_idx").on(t.portalId, t.createdAt.desc()),
    check("portal_requests_status_check", sql`${t.status} in ('pending', 'approved', 'denied')`),
  ],
);

/**
 * A host name this server answers for, other than APP_URL's: an
 * organization's own, added in its settings. Proved by a TXT record holding
 * `token` (lib/portal.ts challengeName), and pointing at the server when it
 * says where (DOMAIN_TARGET), before anything is served at it or a TLS
 * certificate is asked for it (GET /api/v1/domains/check). One serves the
 * app, the `primary` one being where links in email point, or one portal.
 */
export const domains = pgTable("domains", {
  host: text("host").primaryKey(),
  organizationId: uuid("organization_id")
    .notNull()
    .references(() => organizations.id, { onDelete: "cascade" }),
  /** The portal it serves; null: the app. Deleting the portal gives it back to the app. */
  portalId: uuid("portal_id").references(() => portals.id, { onDelete: "set null" }),
  /** The app's default address: links in email point here. One per organization. */
  primary: boolean("primary").notNull().default(false),
  token: text("token").notNull(),
  verifiedAt: timestamp("verified_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("domains_portal_unique").on(t.portalId),
  uniqueIndex("domains_primary_unique").on(t.organizationId).where(sql`${t.primary}`),
]);

/**
 * This database, one row: its id marks the bucket as swept by it
 * (lib/bucket-owners.ts), so a second database on the same bucket is noticed
 * before either sweeps the other's files. Survives a dump and restore.
 */
export const instance = pgTable("instance", {
  singleton: boolean("singleton").primaryKey().default(true),
  id: uuid("id").notNull().defaultRandom(),
}, (t) => [check("instance_singleton_check", sql`${t.singleton}`)]);
